import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** The entry points an out-of-tree module may import on the server. */
const SERVER_ENTRIES = ['.', './server', './agents'] as const;

/**
 * Make the host's own SDK the only one an external module can resolve.
 *
 * The problem this exists to prevent is the server-side twin of "two React
 * instances". The daemon ships as one esbuild bundle, so `@moxxy-ai/companion-sdk`
 * and the `@companion/core` it re-exports are compiled INTO it. An external
 * module under `$COMPANION_HOME/modules/<id>/` that imports the SDK would resolve
 * a second physical copy, with a second `Reply` class. The router decides what to
 * send with `result instanceof Reply`, so every redirect, HTML page and NDJSON
 * export from that module would silently come back as a JSON-wrapped 200. Silent,
 * not loud, which is the worst kind.
 *
 * A symlink to the host's `node_modules` does not fix it either: in a published
 * build there is no unbundled SDK on disk to point at.
 *
 * So the daemon publishes its live namespace objects on a global and writes a
 * tiny package next to the external modules that re-exports them. Node's ordinary
 * upward `node_modules` lookup finds it from any module directory, and every
 * import resolves to the objects the host is already using. One copy by
 * construction, not by convention.
 *
 * The re-export list is the daemon's own namespace keys, which the SDK's tests
 * pin to `packages/sdk/surface.json`. So a symbol in the reviewed ABI is
 * bridged, and one that is not cannot be reached from outside.
 */
export const ABI_GLOBAL = Symbol.for('companion.abi');

export interface AbiBridgeOptions {
  /** `$COMPANION_HOME/modules`; the bridge lands in its `node_modules`. */
  readonly dir: string;
  /** The SDK version this daemon implements; external modules declare a range. */
  readonly version: string;
  /** Entry specifier -> the daemon's live module namespace. */
  readonly namespaces: Readonly<Record<string, Record<string, unknown>>>;
}

/**
 * Write `<dir>/node_modules/@moxxy-ai/companion-sdk`. Rewritten on every boot:
 * it is derived state, and a stale bridge after an upgrade would export the
 * previous release's symbol list.
 */
export function installAbiBridge(opts: AbiBridgeOptions): void {
  const globals = (globalThis as Record<symbol, unknown>)[ABI_GLOBAL] as Record<string, unknown> | undefined;
  const table: Record<string, unknown> = globals ?? {};
  for (const [entry, ns] of Object.entries(opts.namespaces)) table[specifierFor(entry)] = ns;
  (globalThis as Record<symbol, unknown>)[ABI_GLOBAL] = table;

  const pkgDir = join(opts.dir, 'node_modules', '@moxxy-ai', 'companion-sdk');
  rmSync(pkgDir, { recursive: true, force: true });
  mkdirSync(pkgDir, { recursive: true });

  const exportsMap: Record<string, { types?: string; default: string }> = {};
  for (const entry of SERVER_ENTRIES) {
    const file = entry === '.' ? 'index.js' : `${entry.slice(2)}.js`;
    const ns = opts.namespaces[entry] ?? {};
    writeFileSync(join(pkgDir, file), bridgeSource(specifierFor(entry), Object.keys(ns).sort()));
    exportsMap[entry] = { default: `./${file}` };
  }
  writeFileSync(
    join(pkgDir, 'package.json'),
    JSON.stringify(
      {
        name: '@moxxy-ai/companion-sdk',
        version: opts.version,
        type: 'module',
        main: './index.js',
        exports: exportsMap,
        // Not an npm package: written by the daemon, replaced on every boot.
        private: true,
      },
      null,
      2,
    ) + '\n',
  );
}

const specifierFor = (entry: string): string =>
  entry === '.' ? '@moxxy-ai/companion-sdk' : `@moxxy-ai/companion-sdk/${entry.slice(2)}`;

/**
 * Named re-exports rather than `export *`: an ESM binding list has to be static.
 * The names come from the daemon's own namespace objects, not from the snapshot
 * file, so the bridge works in a published bundle where that file is not on
 * disk, and so it cannot promise a symbol the running build does not have. The
 * SDK's own test asserts namespace and snapshot agree, which is what keeps the
 * runtime bridge and the reviewed ABI the same list.
 *
 * Type-only exports have no runtime binding and simply are not here; TypeScript
 * resolved those from the real package when the module was compiled.
 */
function bridgeSource(specifier: string, names: readonly string[]): string {
  return [
    '// Generated by the Companion daemon. Do not edit; rewritten on every boot.',
    `const abi = globalThis[Symbol.for('companion.abi')]?.[${JSON.stringify(specifier)}];`,
    'if (!abi) {',
    `  throw new Error('${specifier} was imported outside a Companion daemon');`,
    '}',
    ...names.map((n) => `export const ${n} = abi[${JSON.stringify(n)}];`),
    '',
  ].join('\n');
}

