#!/usr/bin/env node
/**
 * Generate the two module registries from a build profile.
 *
 *   node scripts/gen-modules.mjs [--profile slim] [--check]
 *
 * Runs automatically on `pnpm install`, `pnpm dev`, `pnpm build` and
 * `pnpm typecheck`, so nobody has to remember it. Set COMPANION_PROFILE=full to
 * make every one of those use the full module set.
 *
 * The profile is the ONLY place a build's module set is named. Both apps import
 * the generated files, which are gitignored: a registry that is committed drifts
 * from the profile the moment someone edits one and not the other.
 *
 * The closure check matters more than the codegen. A profile that omits a
 * module something else depends on used to surface as a boot-time 409 (or a
 * module silently pruned to disabled); here it is a build error naming both
 * sides.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const profilesDir = join(root, 'profiles');
const API_FILE = join(root, 'apps/api/src/modules.generated.ts');
const WEB_FILE = join(root, 'apps/web/src/modules.generated.ts');

function fail(message) {
  process.stderr.write(`${message}\n`);
  process.exit(1);
}

/** `extends` composes profiles so `full` does not restate the slim set. */
function loadProfile(name, seen = new Set()) {
  if (seen.has(name)) fail(`profile '${name}' extends itself`);
  seen.add(name);
  const file = join(profilesDir, `${name}.json`);
  if (!existsSync(file)) {
    const known = readdirSync(profilesDir)
      .filter((f) => f.endsWith('.json'))
      .map((f) => f.replace(/\.json$/, ''));
    fail(`unknown profile '${name}'. Known: ${known.join(', ')}`);
  }
  const profile = JSON.parse(readFileSync(file, 'utf8'));
  const inherited = profile.extends ? loadProfile(profile.extends, seen).modules : [];
  return { ...profile, modules: [...new Set([...inherited, ...profile.modules])] };
}

/**
 * Every module in the repo, read from `src/module.ts` SOURCE.
 *
 * Deliberately not from `dist`: this runs BEFORE the build (the apps import the
 * registries it writes), so on a fresh clone or in a Docker build there is no
 * dist to read. The three fields needed here are plain literals in every
 * manifest, which is why a syntactic read is enough.
 */
/**
 * Blank out object literals nested inside the manifest, so a `required: true` on
 * a CONFIG FIELD is not read as `required: true` on the module. Arrays survive,
 * because `dependsOn` is one.
 */
function withoutNestedObjects(src) {
  let depth = 0;
  let out = '';
  for (const c of src) {
    if (c === '{') depth++;
    else if (c === '}') depth--;
    if (depth <= 1 || (c === '{' && depth === 1)) out += c;
  }
  return out;
}

function loadManifests() {
  const out = new Map();
  for (const entry of readdirSync(join(root, 'modules'), { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const file = join(root, 'modules', entry.name, 'src/module.ts');
    if (!existsSync(file)) continue;
    const src = withoutNestedObjects(readFileSync(file, 'utf8'));
    const id = /\bid:\s*'([^']+)'/.exec(src)?.[1];
    if (!id) fail(`modules/${entry.name}/src/module.ts has no id`);
    if (id !== entry.name) fail(`modules/${entry.name} declares id '${id}'; they must match`);
    const deps = /\bdependsOn:\s*\[([^\]]*)\]/.exec(src)?.[1] ?? '';
    out.set(id, {
      id,
      dependsOn: [...deps.matchAll(/'([^']+)'/g)].map((m) => m[1]),
      required: /\brequired:\s*true/.test(src),
    });
  }
  return out;
}

function validate(selected, manifests) {
  const chosen = new Set(selected);
  const problems = [];
  for (const id of selected) {
    if (!manifests.has(id)) {
      problems.push(`'${id}' is in the profile but no module in modules/ declares it`);
      continue;
    }
    for (const dep of manifests.get(id).dependsOn ?? []) {
      if (!chosen.has(dep)) problems.push(`'${id}' depends on '${dep}', which the profile omits`);
    }
  }
  // A required module missing from the build is worse than a broken dependency:
  // the kernel force-installs required modules and their whole closure, so its
  // absence takes the daemon down at boot rather than degrading.
  for (const [id, m] of manifests) {
    if (m.required && !chosen.has(id)) problems.push(`'${id}' is required and cannot be excluded from a build`);
  }
  if (problems.length) {
    fail(`profile is not buildable:\n${problems.map((p) => `  ${p}`).join('\n')}`);
  }
}

const HEADER = (profile) => `// GENERATED by scripts/gen-modules.mjs from profiles/${profile}.json. Do not edit.
// Change the module set in the profile and re-run: pnpm gen:modules --profile ${profile}
`;

function apiSource(profile, ids) {
  const manifestImports = ids.map((id) => `import ${id}Manifest from '@companion/module-${id}/manifest';`).join('\n');
  const contractImports = ids.map((id) => `import '@companion/module-${id}/contract';`).join('\n');
  const entries = ids
    .map((id) => `  { manifest: ${id}Manifest, load: () => import('@companion/module-${id}/api').then((m) => m.default) },`)
    .join('\n');
  return `${HEADER(profile)}import type { InstalledModule } from '@companion/core/server';
${manifestImports}

// The contract slices open the shared unions (Permission / SpaServerMessage /
// ServiceMap / BusEvents) for this compilation, so the registries stay
// exhaustively typed across exactly this profile's modules. Types are erased;
// the heavy /api code stays behind the lazy load() thunks below.
${contractImports}

/** The daemon's module set for the '${profile}' profile. */
export const MODULES: readonly InstalledModule[] = [
${entries}
];
`;
}

function webSource(profile, ids) {
  const entries = ids.map((id) => `  ${id}: () => import('@companion/module-${id}/client'),`).join('\n');
  return `${HEADER(profile)}import type { ClientLoader } from '@companion/core/client';

/**
 * The SPA's client-module set for the '${profile}' profile. ModulesProvider
 * dynamic-imports ONLY the enabled modules' chunks; a disabled module's JS is
 * never fetched.
 */
export const CLIENT_LOADERS: Readonly<Record<string, ClientLoader>> = {
${entries}
};
`;
}

const argv = process.argv.slice(2);
// `--profile` beats COMPANION_PROFILE beats the shipped default. The env var is
// what lets a contributor pick `full` once and have install / dev / build all
// honour it, instead of remembering a flag on every command.
const profileName = argv.includes('--profile')
  ? argv[argv.indexOf('--profile') + 1]
  : process.env.COMPANION_PROFILE?.trim() || 'slim';
const checkOnly = argv.includes('--check');
if (!profileName) fail('--profile requires a value');

const profile = loadProfile(profileName);
const manifests = loadManifests();
if (!manifests.size) fail('no modules found under modules/');
validate(profile.modules, manifests);

// Topological-ish: dependencies first, so the generated list reads in the order
// the kernel activates. The kernel topo-sorts anyway; this is for humans.
const ordered = [...profile.modules].sort((a, b) => {
  const aDeps = manifests.get(a).dependsOn ?? [];
  const bDeps = manifests.get(b).dependsOn ?? [];
  if (aDeps.includes(b)) return 1;
  if (bDeps.includes(a)) return -1;
  return aDeps.length - bDeps.length;
});

let changed = false;
for (const [file, source] of [
  [API_FILE, apiSource(profile.name, ordered)],
  [WEB_FILE, webSource(profile.name, ordered)],
]) {
  const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (current === source) continue;
  changed = true;
  if (!checkOnly) writeFileSync(file, source);
  process.stdout.write(`${checkOnly ? 'stale' : 'wrote'}  ${relative(root, file)}\n`);
}

if (checkOnly && changed) fail(`\nregistries are stale. Run: pnpm gen:modules --profile ${profile.name}`);
if (!changed) process.stdout.write(`registries already match profile '${profile.name}'\n`);
process.stdout.write(`profile '${profile.name}': ${ordered.length} module(s) [${ordered.join(', ')}]\n`);
