import type { SpaServerMessage } from '@companion/contract';
import type { DaemonConfig } from '../config.js';
import type { Auth } from '../auth/auth.js';
import type { Orchestrator } from '../runs/orchestrator.js';
import type { Fixes } from '../runs/fixes.js';
import type { MoxxyCli } from '../moxxy/cli.js';
import type { Store } from '../store/db.js';
import type { GitHubClient } from '../github/client.js';
import type { GitHubSync } from '../github/sync.js';
import type { Checkouts } from '../git/checkouts.js';
import type { Triage } from '../triage/triage.js';
import type { PrReviews } from '../prs/reviews.js';
import type { PrChecks } from '../prs/checks.js';
import type { GitHubAccounts } from '../github/accounts.js';
import type { Proposals } from '../proposals/proposals.js';
import type { Pipelines } from '../pipelines/pipelines.js';
import type { Automations } from '../automations/automations.js';
import type { WebhookTunnel } from '../moxxy/webhook-tunnel.js';
import type { Skills } from '../skills/skills.js';
import type { Specs } from '../specs/specs.js';
import type { Docs } from '../docs/docs.js';
import type { Assistant } from '../assistant/assistant.js';
import type { Runners } from '../runners/registry.js';

/** Everything the route modules can reach — injected once at boot. */
export interface ApiDeps {
  readonly config: DaemonConfig;
  readonly auth: Auth;
  readonly broadcast: (msg: SpaServerMessage) => void;
  readonly orchestrator: Orchestrator;
  readonly moxxyCli: MoxxyCli | null;
  readonly store: Store;
  readonly github: () => GitHubClient | null;
  readonly githubUser: () => string | null;
  readonly setGithubToken: (token: string) => Promise<{ login: string }>;
  readonly sync: GitHubSync;
  readonly checkouts: Checkouts;
  readonly triage: Triage;
  readonly prReviews: PrReviews;
  readonly prChecks: PrChecks;
  readonly githubAccounts: GitHubAccounts;
  readonly fixes: Fixes;
  readonly proposals: Proposals;
  readonly pipelines: Pipelines;
  readonly automations: Automations;
  readonly webhookTunnel: WebhookTunnel;
  readonly skills: Skills;
  readonly specs: Specs;
  readonly docs: Docs;
  readonly assistant: Assistant;
  readonly runners: Runners;
}
